### ISSUE TITLE
Issues with Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by berezovskyi** [heroku/php-getting-started#3]
I tried to get the app running locally with foreman before pushing to Heroku (which worked like a charm) and hit a lot of issues that I fully described on my blog (https://berezovskiy.me/2015/02/deploying-sample-silex-app-to-heroku/). Here is a short list:

* Ubuntu 14.04 doesn't provide PHP 5.5.11 & Apache 2.4.10 by default
* Script uses completely wrong executable names (see https://github.com/heroku/heroku-buildpack-php/issues/55) etc.

I am surprised to be the first to report this issue: either I was doing something terribly wrong or nobody tried to do this on Ubuntu LTS before.

**Comment by dzuelke** [comment]
It's likely nobody tried this. The tl;dr is that this is not supported - it'll never work on Windows (because FPM only supports Unix), and all the various local Apache/Nginx/PHP setups out there are too different or even borked (such as Debian's/Ubuntu's, with not just different executable names but also different behavior) that this can't be done.

Please do a regular VHost setup to get an app running locally. I know that's not great, but that's what it is with PHP and its requirement for an external web server.
